### ISSUE TITLE
Uknown host

### ISSUE THREAD

**Issue by dyk74** [peregin/gps-overlay-on-video#146]
Hello,
I've tried your software...(nice job) but when I choose "Openstreet map" java return me an error: "Unknown host exception: otile1.mqcdn.com"...
A request: for a new version: is it possibile to add a "dynamic map" too?
On the overlay could I add the map too?

And at the end: I didn't understood how to "manually" add the gauge.
Thank you

**Comment by peregin** [comment]
Hi,

Thanks for reporting the issue, OpenStreetMap is not open source anymore, the usage requires a paid licence.
I have removed it from the list.
You can't add other maps at the moment.
Adding a gauge is not supported yet, the original idea was that you can assemble your own dashboard. Currently you can choose a dashboard type with predefined gauges.
Best,
Levente
