### ISSUE TITLE
GPS Speed smoothing

### ISSUE THREAD

**Issue by daktak** [peregin/gps-overlay-on-video#195]
Feature request

It seems my instantaneous speed from wahoo head unit fluctuates quite a lot. Looking at Garmin VIRB videos this is not the case, perhaps some GPS distance speed calculations can smooth out the values as an optional feature.

**Comment by peregin** [comment]
hi @daktak , one of the recent contributions smoothens the GPS speed, could you please check the current version?

**Comment by daktak** [comment]
Yes just tried a new video + gpx. Looks really good thank you!

**Comment by peregin** [comment]
thanks for the feedback @daktak , then closing this issue.
