### ISSUE TITLE
Video orientation info is not used

### ISSUE THREAD

**Issue by panjacek** [peregin/gps-overlay-on-video#228]
I use DJI action 3 mounted on chest strap for bike and to get best angle I mount it upside down. 

VLC or other modern software can read the orientation metadata and show them properly, however when I try here its upside down so the metadata is ignored.

![image](https://github.com/user-attachments/assets/307a6935-acdd-48eb-ba4a-b6bd9e7bee13)

**Comment by kvr000** [comment]
@panjacek : can you please share the video (or small sample) ?  Is it upside down only in the app and rendering is correct or is it wrong in both?
