### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by JanisE** [peregin/gps-overlay-on-video#29]

**Comment by peregin** [comment]
Hi, 

If you have [sbt](http://www.scala-sbt.org/) installed, then just type
```sbt run```

Let me know how it goes, happy to help and waiting for feedback! :)

Cheers

**Comment by JanisE** [comment]
Thanks, the program opened all right! The video loaded fine. Then I pointed to GPX, and it's been loading it for an hour now. I'll let you know how it goes.

**Comment by peregin** [comment]
That doesn't sound good. Normally the gps file should be processed within seconds, depending on the length. Is there a way that you could share the gpx file with me? so I could check what the issue is?

**Comment by JanisE** [comment]
In short, it looks like loading GPS hangs the program whenever it encounters anything unexpected in the GPX file. E.g., it doesn't like GPX 1.0 (which is what gpsbabel outputs by default), "nan" value for elevation (and probably other elements as well) (which gpsbabel outputs in some cases), and, of course, any elements not supported by the GPX 1.1 specification. Here are some examples:
Works (GPX 1.1): http://pastebin.com/zAq1SPr3
Fails (GPX 1.0): http://pastebin.com/11P371jE
Fails (nan): http://pastebin.com/9yYcBhjv
Fails (speed): http://pastebin.com/iSmJJ1dg

Unfortunately, speed data seems to be included only in GPX 1.0, it is not supported in GPX 1.1 standard anymore, and, it seems to me, there is no speed support also in the Garmin GPX extensions. Do I lose anything if I cannot tell the speed to the overlay program? Is the speed calculated from the given positions as good/accurate as the one given in the NMEA data by the GPS device, do you know?

**Comment by peregin** [comment]
Thanks for the details and gpx snippets! Indeed only version 1.1 of the gpx schema is supported.
In the schema the elevation is numeric value, the binder used in the app (scalaxb) accepts only a numeric value for this element, will fail with nan.
You're right, version 1.1 is not supporting the speed, but the app calculates the speed based on the coordinates and timestamp of the coordinates.

So the overlay program will do the speed calculations. I can't answer you about the accuracy compared with the NMEA data, depends on the algorithm used by the device for speed calculation.
The overlay app uses the [Haversine formula](http://en.wikipedia.org/wiki/Haversine_formula) and includes the elevation as well in the final formula.
