### ISSUE TITLE
sbt.ResolveException: unresolved dependency: org.mockito on run

### ISSUE THREAD

**Issue by bigtreacle** [peregin/gps-overlay-on-video#30]
after running `sbt run` I get the following:

`[error] (*:update) sbt.ResolveException: unresolved dependency: org.mockito#mockito-all;1.10.10: not found`

**Comment by bigtreacle** [comment]
looks like version 1.1.10 isn't available in any repos - replaced with 1.10.16 and compiled without error.  will continue testing.

**Comment by peregin** [comment]
Apologies for the late reply. I just pulled in the change #32 for bumping the mockito version to 1.10.16.
