### ISSUE TITLE
unresolved dependencies

### ISSUE THREAD

**Issue by ilievdh** [peregin/gps-overlay-on-video#35]
...
[info] Resolving xuggle#xuggle-xuggler;5.4 ...
[warn]  module not found: xuggle#xuggle-xuggler;5.4
...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: xuggle#xuggle-xuggler;5.4: not found
[warn]  :: org.mockito#mockito-all;1.10.10: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: xuggle#xuggle-xuggler;5.4: not found
[error] unresolved dependency: org.mockito#mockito-all;1.10.10: not found
[error] Total time: 66 s, completed May 24, 2017 7:52:03 PM

**Comment by peregin** [comment]
Unfortunately the original [Xuggle](http://xuggle.googlecode.com/svn/trunk/repo/share/java/) repository does not exists anymore. I've added an explicit URL to the [jar](https://files.liferay.com/mirrors/xuggle.googlecode.com/svn/trunk/repo/share/java/xuggle/xuggle-xuggler/5.4/xuggle-xuggler-5.4.jar) file in the build.sbt.
