### ISSUE TITLE
can i use this software also on linux ubuntu?

### ISSUE THREAD

**Issue by Bigjuergo** [peregin/gps-overlay-on-video#37]

**Comment by klausx** [comment]
i use it from time to time on ubuntu 17.04

**Comment by Bigjuergo** [comment]
can you please tell me how to compile the programm in linux?

**Comment by Bigjuergo** [comment]
i installed sbt
but when i run the programm with sbt run

execution stops directly after with:
Getting org.scala-sbt sbt 0.13.16 ...

**Comment by Bigjuergo** [comment]
ok after some time it started to compile, but after i type sbt run again i got the error:

> root@bigjuergo-X550LA:/home/bigjuergo/Downloads/gps-overlay-on-video-master# sbt run
> [info] Loading project definition from /home/bigjuergo/Downloads/gps-overlay-on-video-master/project
> [info] Set current project to telemetry-on-video (in build file:/home/bigjuergo/Downloads/gps-overlay-on-video-master/)
> [info] Running peregin.gpv.App 
> 19:24:47.038 [run-main-0] INFO  peregin.gpv.App$ - initializing...
> [error] (run-main-0) java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
> java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
> 	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
> 	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
> 	at com.jgoodies.looks.LookUtils.isLowResolution(LookUtils.java:480)
> 	at com.jgoodies.looks.LookUtils.<clinit>(LookUtils.java:249)
> 	at com.jgoodies.looks.plastic.PlasticLookAndFeel.<clinit>(PlasticLookAndFeel.java:135)
> 	at peregin.gpv.gui.Goodies$.initLookAndFeel(Goodies.scala:26)
> 	at peregin.gpv.App$.<init>(App.scala:25)
> 	at peregin.gpv.App$.<clinit>(App.scala)
> 	at peregin.gpv.App.main(App.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> [trace] Stack trace suppressed: run last compile:run for the full output.
> java.lang.RuntimeException: Nonzero exit code: 1
> 	at scala.sys.package$.error(package.scala:27)
> [trace] Stack trace suppressed: run last compile:run for the full output.
> [error] (compile:run) Nonzero exit code: 1
> [error] Total time: 2 s, completed 10.11.2017 19:24:47

**Comment by Bigjuergo** [comment]
**ok now it works!**

i had to run the following commands

> sudo dpkg -l | grep openjdk  

This is to verify you are actually running the headless version of JAVA, so no graph library available.

> sudo apt-get remove openjdk-8-jre-headless

This is to remove headless version.

> sudo apt-get install openjdk-8-jre

This is to install non-headless version of java.

i hope this helps anyone who has the same problems!

:-)

**Comment by Bigjuergo** [comment]
i made a tutorial how to use this program https://www.youtube.com/watch?v=yOvT8IoDUPA

**Comment by Schrottie** [comment]
And here is – in german – a small "HowTo" for this software: https://blog.dafb-o.de/gps-overlay-on-video-howto-anzeige-von-gps-daten-in-videos-mit-linux/

**Comment by peregin** [comment]
hi @Bigjuergo , @Schrottie ,
Thank you for your amazing videos and tutorials! 
I did an update to the readme.md file on this branch [how-to](https://github.com/peregin/gps-overlay-on-video/tree/how-to) branch. If you are fine with and no objection from your side I'm more than happy to add these links to the master branch.
Thanks again for your work!

PS. This sounds like a pull request review on the how-to branch :)
