### ISSUE TITLE
Failing compilation in Debian

### ISSUE THREAD

**Issue by jgpallero** [peregin/gps-overlay-on-video#42]
Hello:

I'm trying to compile the software in Debian and I've obtained this error:

```
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 1 s, completed 01-mar-2019 10:09:02
```
If I run last compile:run I obtain anything

**Comment by Marlow925** [comment]
Hi,
I had the same problem on Ubuntu. Then downloaded the source and tried that. It failed to compile.

So I dug a bit deeper and the problem relates to Java 10 and 11 and an still open issue with scala-sbt: https://github.com/ohnosequences/sbt-github-release/issues/28

I have Java 11 installed and the following fix solved it for me: 

  on JDK 11, add this to projects/plugins.sbt to make it work:
  libraryDependencies += "com.sun.activation" % "javax.activation" % "1.2.0"

Hope that helps.

/M

**Comment by peregin** [comment]
@jgpallero , @Marlow925 thanks for reporting it and providing a fix for it! Indeed, from Java 9 the activation library was deprecated. I've added the javax.activation library to the dependencies.
