### ISSUE TITLE
Endless loop loading GPX 

### ISSUE THREAD

**Issue by tve** [peregin/gps-overlay-on-video#43]
I'm trying to load a GPX file and the loading indicator just spins forever. The GPX file can be found at https://s3.amazonaws.com/s3.voneicken.com/20190517_221037.gpx
I'm running the latest release jar on linux:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```

**Comment by peregin** [comment]
@tve thanks for the feedback, I've updated the parsing logic, a few data points from the beginning of the gpx stream were missing the elevation data.

**Comment by tve** [comment]
Works now, thanks!
