### ISSUE TITLE
Error compilation in Debian

### ISSUE THREAD

**Issue by jgpallero** [peregin/gps-overlay-on-video#46]
Hello:
I'm trying to use the software in Debian using sbt 0.13.13 (the version in the Sid repositories), and JRE 14. After sbt run I obtain lots of errors which I show in the attached file
[errors-gps-overlay.txt](https://github.com/peregin/gps-overlay-on-video/files/3810499/errors-gps-overlay.txt)

**Comment by peregin** [comment]
hi @jgpallero ,

Thanks for reporting the issue! I just added a small shell script into the root folder, called `run.sh` that will run the application with the latest package published from github.
Could you try to run it from the script? It won't required different `sbt` or `scala` , it runs the latest fat jar.

Best regards,
Levente

**Comment by jgpallero** [comment]
It works! Thank you
