### ISSUE TITLE
Feature req

### ISSUE THREAD

**Issue by c0ff3e** [peregin/gps-overlay-on-video#91]
Hello.

Tested it today, found that it dont seem to be able to handle gorpo7 4k video.
But i would love to see a overlay as the map used to sync, but as a overlay, thats something we that drive on racetracks would love to have.

Please let me know if i can help or assist in any way.

Br
Coffe

**Comment by KivraChristoffer** [comment]
closing, duplicate of #47

**Comment by peregin** [comment]
closing as duplicate of #47
