### ISSUE TITLE
Shift works on preview but not on rendered video

### ISSUE THREAD

**Issue by lifebarier** [peregin/gps-overlay-on-video#92]
Shifting gps forth or back seems to work when I am watching preview, but when video is 'converted' it seems that gps is applied without shift.

**Comment by raspberryrippl3** [comment]
I noticed this but eventually got it working by trying to get the yellow and blue markers at the same point by clicking on the elevation graph

**Comment by danieldean** [comment]
I noticed this too. I worked around it by trimming my GPX file to suit but would be good if the bug could be fixed.
